<?php
namespace LeKoala\Base\Theme;

use LeKoala\Base\Dev\BuildTask;
use SilverStripe\Control\Director;

/**
 * Some useful features to help you when building your themes
 */
class ThemeAssistantTask extends BuildTask
{
    use KnowsThemeDir;

    protected $description = 'Helps you building themes';
    private static $segment = 'ThemeAssistantTask';

    public function isEnabled()
    {
        return Director::isDev();
    }

    public function init()
    {
        $componentsFolder = $this->getComponentsScssFolder();
        if (is_dir($componentsFolder)) {
            $this->message("Building components");

            $allComponents = glob($componentsFolder . '/*.scss');
            $scssFile = dirname($componentsFolder) . '/_components.scss';
            $data = '/* This file is automatically generated */' . "\n";
            $i = count($allComponents);
            foreach ($allComponents as $componentFile) {
                $componentName = trim(pathinfo($componentFile, PATHINFO_FILENAME), '_');
                $data .= '@import "components/' . $componentName . '";' . "\n";
            }
            file_put_contents($scssFile, $data);

            $this->message("Indexed $i components in _components.scss");
        } else {
            $this->message("There is no 'components' folder in your theme. Create one and put your sass files in there.");
        }
    }

    protected function getScssFolder($name = '')
    {
        return Director::baseFolder() . DIRECTORY_SEPARATOR . $this->getThemeDir() . '/sass/' . $name;
    }

    protected function getComponentsScssFolder()
    {
        return $this->getScssFolder('components');
    }

    protected function getVendorScssFolder()
    {
        return $this->getScssFolder('vendor');
    }
}
