---
Name: base-mysql
After: '#databaseconnectors'
---
# Because there is really no reason to use regular utf8
SilverStripe\ORM\Connect\MySQLDatabase:
  connection_charset: utf8mb4
  connection_collation: utf8mb4_unicode_ci
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
# You also have to be aware that if you set an index on a big char or varchar field
# which is utf8mb4 encoded, you have to divide the max index prefix length of 767 bytes (or 3072 bytes) by 4
# resulting in 191. This is because the maximum length of a utf8mb4 character is four bytes.
# For a utf8 character it would be three bytes resulting in max index prefix length of 254.
# https://github.com/silverstripe/silverstripe-framework/issues/8062
---
Name: base-fieldtypes
After: '#corefieldtypes'
---
SilverStripe\Core\Injector\Injector:
  BinaryIP:
    class: LeKoala\Base\ORM\FieldType\DBBinaryIP
  Color:
    class: LeKoala\Base\ORM\FieldType\DBColor
  Country:
    class: LeKoala\Base\ORM\FieldType\DBCountry
  Json:
    class: LeKoala\Base\ORM\FieldType\DBJson
  Phone:
    class: LeKoala\Base\ORM\FieldType\DBPhone
  Timezone:
    class: LeKoala\Base\ORM\FieldType\DBTimezone
  Website:
    class: LeKoala\Base\ORM\FieldType\DBWebsite
  NumericVarchar:
    class: LeKoala\Base\ORM\FieldType\DBNumericVarchar
  NiceEnum:
    class: LeKoala\Base\ORM\FieldType\DBNiceEnum
  Currency:
    class: LeKoala\Base\ORM\FieldType\DBBetterCurrency
  Decimal:
    class: LeKoala\Base\ORM\FieldType\DBBetterDecimal
  Percentage:
    class: LeKoala\Base\ORM\FieldType\DBBetterPercentage
  Date:
    class: LeKoala\Base\ORM\FieldType\DBBetterDate
  DBNullableClassName:
    class: LeKoala\Base\ORM\FieldType\DBNullableClassName
  # See DataObjectSchema:492
  ForeignKey:
    class: LeKoala\Base\ORM\FieldType\DBBetterForeignKey
  PolymorphicForeignKey:
    class: LeKoala\Base\ORM\FieldType\DBNullablePolymorphicForeignKey
  UntranslatedVarchar:
    class: LeKoala\Base\ORM\FieldType\DBUntranslatedVarchar
---
Name: base-searchfilters
After: '#coresearchfilters'
---
SilverStripe\Core\Injector\Injector:
  DataListFilter.Regexp:
    class: LeKoala\Base\ORM\Filters\RegexpFilter
  RegexpFilter: '%$DataListFilter.Regexp'
