---
Name: base-security
After:
  - '#coresecurity'
---
# https://github.com/silverstripe/silverstripe-framework/issues/9346
SilverStripe\Control\Session:
  cookie_secure: true
  cookie_name_secure: 'PHPSESSID'
SilverStripe\Security\Security:
  login_recording: true
  # don't trigger 2fa for whitelisted ips. Use with admin_ip_whitelist
  # this will effectively lower your security but will make life easier for admin users
  disable_2fa_whitelisted_ips: false
  # restrict admin login to a set of ips when 2fa is not set
  admin_ip_whitelist: []
  # ip address for dev and default admin
  dev_ip_whitelist: []
  window_2fa: 8
  extensions:
    - LeKoala\Base\Security\BaseSecurityExtension
# Extensions
SilverStripe\Admin\SecurityAdmin:
  extensions:
    - LeKoala\Base\Security\BaseSecurityAdminExtension
SilverStripe\Security\Member:
  extensions:
    - LeKoala\Base\Security\BaseMemberExtension
# Prevent any destructive operation and safely migrate
SilverStripe\Assets\FileMigrationHelper:
  delete_invalid_files: false
# Extensions for login/logout actions
SilverStripe\Security\MemberAuthenticator\LoginHandler:
  extensions:
    - LeKoala\Base\Security\LoginHandlerExtension
SilverStripe\Security\MemberAuthenticator\LogoutHandler:
  extensions:
    - LeKoala\Base\Security\LogoutHandlerExtension
SilverStripe\Security\MemberAuthenticator\LostPasswordHandler:
  extensions:
    - LeKoala\Base\Security\LostPasswordHandlerExtension
# Injector
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: 'LeKoala\Base\Security\MemberLoginForm'
  SilverStripe\Security\MemberAuthenticator\MemberAuthenticator:
    class: 'LeKoala\Base\Security\BaseAuthenticator'
  SilverStripe\Security\MemberAuthenticator\ChangePasswordHandler:
    class: 'LeKoala\Base\Security\TwoFactorChangePasswordHandler'
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: '%$LeKoala\Base\Security\BaseAuthenticator'
  # SilverStripe\Security\CMSSecurity:
  #    properties:
  #    Authenticators:
  #      cms: '%$LeKoala\Base\Security\BaseAuthenticator'
---
Name: base-dev-security
Except:
  environment: live
---
SilverStripe\Control\Session:
  # don't kill session when toggling browser inspector/responsive mode
  strict_user_agent_check: false
