---
Name: base-security
After:
  - '#coresecurity'
---
# Global settings
LeKoala\Base\Security\BaseAuthenticator:
  # if you set this to true, you need to apply TwoFactorMemberExtension
  enable_2fa: false
  # need enable_2fa set to true => will only check users with cms permission
  enable_2fa_admin_only: false
  # don't trigger 2fa for whitelisted ips. Only metters if you set SilverStripe\Security\Security.admin_ip_whitelist
  disable_2fa_whitelisted_ips: false
SilverStripe\Security\Security:
  login_recording: true
  extensions:
    - LeKoala\Base\Security\BaseSecurityExtension
# Extensions
SilverStripe\Admin\SecurityAdmin:
  extensions:
    - LeKoala\Base\Security\BaseSecurityAdminExtension
SilverStripe\Security\Member:
  extensions:
    - LeKoala\Base\Security\BaseMemberExtension
LeKoala\Base\Security\MemberAudit:
  extensions:
    - LeKoala\CommonExtensions\IPExtension
# Prevent any destructive operation and safely migrate
SilverStripe\Assets\FileMigrationHelper:
  delete_invalid_files: false
# Extensions for login/logout actions
SilverStripe\Security\MemberAuthenticator\LoginHandler:
  extensions:
    - LeKoala\Base\Security\LoginHandlerExtension
SilverStripe\Security\MemberAuthenticator\LogoutHandler:
  extensions:
    - LeKoala\Base\Security\LogoutHandlerExtension
SilverStripe\Security\MemberAuthenticator\LostPasswordHandler:
  extensions:
    - LeKoala\Base\Security\LostPasswordHandlerExtension
# Injector
SilverStripe\Core\Injector\Injector:
  SilverStripe\Security\MemberAuthenticator\MemberAuthenticator:
    class: 'LeKoala\Base\Security\BaseAuthenticator'
  SilverStripe\Security\MemberAuthenticator\MemberLoginForm:
    class: 'LeKoala\Base\Security\MemberLoginForm'
  SilverStripe\Security\Security:
    properties:
      Authenticators:
        default: '%$LeKoala\Base\Security\BaseAuthenticator'
  # SilverStripe\Security\CMSSecurity:
  #    properties:
  #    Authenticators:
  #      cms: '%$LeKoala\Base\Security\BaseAuthenticator'
---
Name: base-dev-security
Except:
  environment: live
---
SilverStripe\Control\Session:
  # don't kill session when toggling browser inspector/responsive mode
  strict_user_agent_check: false
