<?php
namespace LeKoala\Base\Dev;

use SilverStripe\Core\Kernel;
use LeKoala\Base\Blocks\Block;
use LeKoala\Base\Dev\BuildTask;
use SilverStripe\View\SSViewer;
use SilverStripe\Core\ClassInfo;
use SilverStripe\Control\Director;
use SilverStripe\View\ThemeManifest;
use LeKoala\Base\Theme\KnowsThemeDir;
use SilverStripe\Control\HTTPRequest;
use SilverStripe\Core\Injector\Injector;
use SilverStripe\Dev\DevBuildController;
use SilverStripe\View\ThemeResourceLoader;
use SilverStripe\Core\Manifest\ClassLoader;

/**
 * Assist in building blocks for your website
 *
 * @author lekoala
 */
class BlocksCreateTask extends BuildTask
{
    use KnowsThemeDir;

    protected $title = "Create Blocks";
    protected $description = 'Create block classes and styles based on your templates.';
    private static $segment = 'BlocksCreateTask';

    public function init(HTTPRequest $request)
    {
        $themeBlocksPath = Director::baseFolder() . DIRECTORY_SEPARATOR . $this->getThemeDir() . '/templates/Blocks';
        $mysiteBlocksPath = Director::baseFolder() . DIRECTORY_SEPARATOR . project() . '/templates/Blocks';

        $classes = Block::listTemplates();

        $files = [];
        $files = array_merge($files, glob($themeBlocksPath . '/*.ss'));
        $files = array_merge($files, glob($mysiteBlocksPath . '/*.ss'));

        if (empty($files)) {
            $this->message("No blocks found");
            $this->message("Please make sure you have blocks in $themeBlocksPath or in $mysiteBlocksPath");
        }

        $classCreated = false;
        $allBlocks = [];
        foreach ($files as $file) {
            $result = $this->createBlockClass($file, $classes);
            if ($result) {
                $classCreated = true;
            }
            $result = $this->createStyles($file);

            $allBlocks[] = pathinfo($file, PATHINFO_FILENAME);
        }

        $this->message("Refresh all styles");

        $scssFile = dirname($this->getScssFolder()) . '/_blocks.scss';
        $data = '/* This file is automatically generated */' . "\n";
        foreach ($allBlocks as $blockName) {
            $data .= '@import "blocks/' . $blockName . '";' . "\n";
        }
        file_put_contents($scssFile, $data);

        // A new class was added, regenerate the manifest
        if ($classCreated) {
            $this->regenerateClassManifest();
        }
    }

    protected function getScssFolder()
    {
        return Director::baseFolder() . DIRECTORY_SEPARATOR . $this->getThemeDir() . '/sass/blocks';
    }

    protected function createStyles($file)
    {
        $name = pathinfo($file, PATHINFO_FILENAME);
        $scssBlocksPath = $this->getScssFolder();

        $scssFile = $scssBlocksPath . '/_' . $name . '.scss';
        if (is_file($scssFile)) {
            $this->message("Skip styles for $name");
            return false;
        }

        $this->message("Creating styles for $name", "created");

        $data = <<<SCSS
.Block-$name {

}
SCSS;
        file_put_contents($scssFile, $data);

        return true;
    }

    protected function createBlockClass($file, $classes)
    {
        $name = pathinfo($file, PATHINFO_FILENAME);
        if (isset($classes[$name])) {
            $this->message("Skip block $name");
            return false;
        }
        $this->message("Creating block $name", "created");

        $mysite = Director::baseFolder() . '/mysite/code/Blocks';
        if (!is_dir($mysite)) {
            mkdir($mysite);
        }

        $filename = $mysite . DIRECTORY_SEPARATOR . $name . '.php';

        $data = <<<PHP
<?php
use SilverStripe\Forms\FieldList;
use LeKoala\Base\Blocks\BaseBlock;
use LeKoala\Base\Blocks\BlockFieldList;

class $name extends BaseBlock
{
public function updateFields(BlockFieldList \$fields)
{
}

public function Collection()
{
    return false;
}

public function SharedCollection()
{
    return false;
}
}
PHP;
        \file_put_contents($filename, $data);

        return true;
    }
}
